name: chemistry
channels:
  - conda-forge
dependencies:
  - python=3.12
  - rdkit=2025.09.5
  - vina=1.2.7
  - meeko=0.7.1
  - pdbfixer=1.12
  - openmm=8.4.0
  - pydantic=2.11.7
  - httpx=0.28.1
  - pandas=2.2.3
  - pip
